### ISSUE TITLE
Api docs not accessible

### ISSUE THREAD

**Issue by gamefundas** [GreenCom-Networks/Franz-manager-api#6]
Not sure if I am looking at the right place but the API docs is not accessible using the URL below
http://franz-api-server:1337/franz-manager-api/apidoc/

Does it need to be bundled in some way in to the jar?

**Comment by mumrau** [comment]
I do believe that you are actually looking at the right place, except possibly for the `hostname` but you probably tweaked it.

Can you try access `your-domain:1337/franz-manager-api/status`? You should get a `200 OK` alongside a JSON payload looking like ```{
"id": "franz-manager-api",
"status": "OK"
}```

If not, then you most likely have a network misconfiguration, or a bootstrapping issue.

(FYI, it is added at docker build time to the image.)

**Comment by gamefundas** [comment]
Pardon me, it had to do with some firewall rules. I managed to get this working.
